### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by oterrien**

### CODE REVIEW

**Comment by oterrien** [comment]
approved

**Comment by oterrien** [comment]
rejected

**Comment by oterrien** [comment]
approved

**Comment by oterrien** [comment]
to be reviewed

**Comment by oterrien** [comment]
rejected

**Comment by oterrien** [comment]
approved

**Comment by oterrien** [comment]
to be reviewed

**Comment by oterrien** [comment]
approved

**Comment by oterrien** [comment]
to be reviewed

**Comment by oterrien** [comment]
auto-approved

**Comment by oterrien** [comment]
approved

**Comment by oterrien** [comment]
approved

**Comment by oterrienGmail** [comment]
@oterrien : auto-approval is not authorized for this repository
Someone else should review your code.
If nobody is available, type **auto-approved** and provide a reason.
But pay attention to this workaround is traced.

**Comment by oterrien** [comment]
auto-approved

**Comment by oterrien** [comment]
auto-approved

**Comment by oterrien** [comment]
auto-approved

**Comment by oterrienGmail** [comment]
@oterrienGmail, @oterrien : oterrien has approved own pull request for the given reason:
`auto-approved`

**Comment by oterrien** [comment]
approved

**Comment by oterrien** [comment]
ok to merge

**Pull request closed without merging**
