### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by oterrien**

### CODE REVIEW

**Comment by oterrien** [comment]
test

**Comment by oterrien** [comment]
Approved

**Comment by oterrien** [comment]
Approved

**Comment by oterrien** [comment]
Approved

**Comment by oterrien** [comment]
Approved

**Comment by oterrien** [comment]
Approved

**Comment by oterrien** [comment]
Approved

**Comment by oterrien** [comment]
Approved

**Comment by oterrien** [comment]
approved

**Comment by oterrien** [comment]
approved

**Comment by oterrien** [comment]
test

**Comment by oterrien** [comment]
approved

**Comment by oterrien** [comment]
reject

**Comment by oterrien** [comment]
approve

**Comment by oterrien** [comment]
OK

**Comment by oterrien** [comment]
OK

**Comment by oterrien** [comment]
approved

**Comment by oterrienGmail** [comment]
@oterrien : auto-approval is not authorized for this repository
Someone else should review your code.
If nobody is available, type auto-approved and provide a valid reason.
But pay attention to this workaround is traced.

**Comment by oterrienGmail** [comment]
@oterrien : auto-approval is not authorized for this repository
Someone else should review your code.
If nobody is available, type auto-approved and provide a valid reason.
But pay attention to this workaround is traced.

**Comment by oterrienGmail** [comment]
@oterrien : auto-approval is not authorized for this repository
Someone else should review your code.
If nobody is available, type auto-approved because and provide a valid reason.
But pay attention to this workaround is traced.

**Comment by oterrienGmail** [comment]
@oterrien : oterrien has auto-approved this pull request for the given reason:
`auto-approved because`

**Comment by oterrienGmail** [comment]
@oterrien : oterrien has **auto-approved** this pull request for the given reason:
`auto-approved because`

**Comment by oterrienGmail** [comment]
@oterrien : oterrien has **auto-approved** this pull request for the given reason:
`auto-approved because`

**Comment by oterrienGmail** [comment]
@oterrien : oterrien has **auto-approved** this pull request for the given reason:
`auto-approved because`

**Comment by oterrienGmail** [comment]
@oterrien : oterrien has **auto-approved** this pull request for the given reason:
`auto-approved because`

**Comment by oterrienGmail** [comment]
@oterrien : oterrien has **auto-approved** this pull request for the given reason:
`auto-approved because`

**Comment by oterrienGmail** [comment]
@oterrien : oterrien has **auto-approved** this pull request for the given reason:
`auto-approved because`

**Comment by oterrienGmail** [comment]
@oterrien : oterrien has **auto-approved** this pull request for the given reason:
`auto-approved because`

**Comment by oterrienGmail** [comment]
@oterrien : oterrien has **auto-approved** this pull request for the given reason:
`auto-approved because`

**Comment by oterrienGmail** [comment]
@oterrien : oterrien has **auto-approved** this pull request for the given reason:
`auto-approved because`

**Comment by oterrienGmail** [comment]
@oterrien : auto-approval is not authorized for this repository
**Someone else should review your code.**
If nobody is available, type "**auto-approved because** {reason}" and provide a **valid** reason.
But **pay attention** to this workaround is **traced**.

**Comment by oterrienGmail** [comment]
@oterrien : auto-approval is not authorized for this repository
**Someone else should review your code.**
If nobody is available, type "**auto-approved because** {reason}" and provide a **valid** reason.
But **pay attention** to this workaround is **traced**.

**Comment by oterrienGmail** [comment]
@oterrien : auto-approval is not authorized for this repository
**Someone else should review your code.**
If nobody is available, type "**auto-approved because** {reason}" and provide a **valid** reason.
But **pay attention** to this workaround is **traced**.

**Comment by oterrienGmail** [comment]
@oterrien : auto-approval is not authorized for this repository
**Someone else should review your code.**
If nobody is available, type "**auto-approved because** {reason}" and provide a **valid** reason.
But **pay attention** to this workaround is **traced**.

**Comment by oterrienGmail** [comment]
@oterrien : auto-approval is not authorized for this repository
**Someone else should review your code.**
If nobody is available, type "**auto-approved because** {reason}" and provide a **valid** reason.
But **pay attention** to this workaround is **traced**.

**Comment by oterrienGmail** [comment]
@oterrien : oterrien has **auto-approved** this pull request for the given reason:
`auto-approved because I want`

**Comment by oterrienGmail** [comment]
@oterrien : oterrien has **auto-approved** this pull request for the given reason:
`auto-approved because I want`

**Comment by oterrienGmail** [comment]
@oterrien : oterrien has **auto-approved** this pull request for the given reason:
`auto-approved because I want`

**Pull request closed without merging**
